refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  logfile:
    kind: rolling_file
    path: "log/remote-control.log"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller:
        kind: fixed_window
        count: 100
        pattern: "log/remote-control{}.log"
root:
  level: debug
  appenders:
    - stdout
    - logfile
